/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Semi;

import RCP.RCPDAO;
import RCP.RCPDB;
import RCP.RCPDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author iiuu2
 */
public class SearchRCP extends javax.swing.JFrame implements ActionListener{
    
    public static final int SHOW_RECIPE=1; //레시피 검색
    public static final int ADD_MEAL=2; //식단등록
    
    private int rcpFlag;
    
    private RCPDAO rcpDao;
    private String[] colNames={"레시피 이름","재료","칼로리"};
    private DefaultTableModel model=new DefaultTableModel();
    /** Creates new form SearchRCP */
    public SearchRCP() {
        initComponents();
        
        init();
        addEvent();
        
    }
    public SearchRCP(int flag) {
        this();
        this.rcpFlag = flag;
        rcpProc();
    }
 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbView = new javax.swing.JTable();
        tfSearch = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        btMore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "레시피 검색", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("맑은 고딕", 1, 20))); // NOI18N

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("레시피"));

        tbView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "레시피 이름", "재료", "칼로리"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbView);

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        btSearch.setText("검색");

        btMore.setText("자세히보기");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMore)
                .addContainerGap(60, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch)
                    .addComponent(btMore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchRCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchRCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchRCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchRCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchRCP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMore;
    private javax.swing.JButton btSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbView;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables

    private void init() {
        
        rcpDao = new RCPDAO();
        try {
            selectAll();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addEvent() {
        btSearch.addActionListener(this);
        tfSearch.addActionListener(this);
        btMore.addActionListener(this);
        
        tfSearch.addMouseListener(new EventHandler());
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == btSearch || e.getSource() == tfSearch){
            try {
                String rcpName = tfSearch.getText();
                selectByName(rcpName);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else if(e.getSource() == btMore){
            
            
           // SearchRCP f = new SearchRCP(SHOW_RECIPE);
            int row = tbView.getSelectedRow();
            
            if(row != -1){
                
                Object objName =tbView.getValueAt(row, 0);
                tfSearch.setText(objName.toString());
                
                RCPView fr = new RCPView();
                fr.setVisible(true);
            }
            
        } //if
    }

    private void rcpProc() {
        
        if(rcpFlag == SHOW_RECIPE){
            setTitle("레시피 검색");
            btMore.setText("자세히보기");
            
        }else if(rcpFlag == ADD_MEAL ){
            setTitle("식단 검색");
            btMore.setText("식단 등록");
            Meal.addMeal();
        }
    }
    
    
    class EventHandler extends MouseAdapter implements ItemListener{

        @Override
        public void mouseClicked(MouseEvent e) {
           if(e.getSource() == tbView){
                          
               int row = tbView.getSelectedRow();
               if(row != -1){
                   Object objName =tbView.getValueAt(row, 0);
                   tfSearch.setText(objName.toString());
                   
              
               }
                
           }     
            
        }

        @Override
        public void itemStateChanged(ItemEvent e) {
        }


    }
    

    
    private void selectAll() throws SQLException {
        List<RCPDTO> list = rcpDao.selectAll();
        
        if(list == null || list.isEmpty()){
            JOptionPane.showMessageDialog(this, "데이터가 없습니다.");
            return;
        }
        
        String[][] data = new String[list.size()][colNames.length];
        for(int i = 0; i < list.size(); i++){
            RCPDTO dto = list.get(i);
            
            data[i][0] = dto.getRcpName();
            data[i][1] = dto.getFdName();
            data[i][2] = dto.getCalorie() + "  Kcal";
  
        }
        
        model.setDataVector(data, colNames);
        tbView.setModel(model);
        
        tbView.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbView.getColumnModel().getColumn(1).setPreferredWidth(400);
        tbView.getColumnModel().getColumn(2).setPreferredWidth(10);
   
       
       DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
       dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
       tbView.getColumnModel().getColumn(2).setCellRenderer(dtcr);
       
       tbView.getTableHeader().setReorderingAllowed(false);

    }

    private void selectByName(String rcpName) throws SQLException {
       rcpName = tfSearch.getText();
       
       
       //2
       rcpDao = new RCPDAO();       
       List<RCPDTO> list = rcpDao.selectByName(rcpName);
       
       if(list == null || list.isEmpty()){
            JOptionPane.showMessageDialog(this, "제품이 없습니다");
       }
       
       //3
       String[] colNames = {"레시피 이름", "재료", "칼로리"};
       String[][] data = new String[list.size()][colNames.length];
       
       for(int i = 0; i < list.size(); i++){
           RCPDTO dto = list.get(i);
           
           data[i][0] = dto.getRcpName();
           data[i][1] = dto.getFdName();
           data[i][2] = dto.getCalorie()+"  Kcal";
           
       }
       
       DefaultTableModel model = new DefaultTableModel();
       model.setDataVector(data, colNames);
       tbView.setModel(model);

       tbView.getColumnModel().getColumn(0).setPreferredWidth(50);
       tbView.getColumnModel().getColumn(1).setPreferredWidth(400);
       tbView.getColumnModel().getColumn(2).setPreferredWidth(10);
       
       DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
       dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
       tbView.getColumnModel().getColumn(2).setCellRenderer(dtcr);
       
       tbView.getTableHeader().setReorderingAllowed(false);
       
    }



}
